### ISSUE TITLE
Text Formatting Issue CE text/media

### ISSUE THREAD

**Issue by myrnagoe** [TYPO3incubator/surfcamp-team4#141]
**Issue:**
The text is not formatted correctly in the second "Normal" backend layout. Additionally, there are two "Normal" backend layout columns with the same name, causing confusion. 

![Image](https://github.com/TYPO3incubator/surfcamp-team4/assets/166131497/5f47fb1c-6ae8-400b-a3a4-7b82bed195eb)

![Image](https://github.com/TYPO3incubator/surfcamp-team4/assets/166131497/7d29aa15-02b0-458e-800d-7e1c9155f413)

**Expected Outcome:**

![Image](https://github.com/TYPO3incubator/surfcamp-team4/assets/166131497/1b3756db-9d2d-43fe-a155-0d7bd380e1bc)

-> Text should be formatted correctly in the second "Normal" backend layout.
-> Each backend layout column should have a unique name to avoid confusion or there should be only one option.

**Comment by pixeldesu** [comment]
I fixed the label of the bottom-most colPos in #150. This now also makes it clear that (as it already was with internal naming) that only the CTA, or other full-width elements, belong into that colPos.

![image](https://github.com/user-attachments/assets/f2f5fc3b-a429-4aa7-b999-5fa987fcb07c)

If the content is structured like this, with both the text element and the sponsors element being in the "Normal" column, the page looks like this:

![image](https://github.com/user-attachments/assets/97d79dad-b033-4071-8647-d7bf9a1105bd)
